# Generated by Django 6.0.2 on 2026-02-09 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('FARMER', 'Farmer'), ('STARTUP', 'Beneficiation Startup')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_needed', models.CharField(max_length=100)),
                ('quantity_needed_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_by_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='marketplace.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.userprofile')),
            ],
        ),
    ]
