# Generated by Django 6.0.2 on 2026-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
